#!/usr/bin/with-contenv sh
echo "Starte socat mit: $REMOTE_HOST:$REMOTE_PORT <-> $DEVICE_LINK" > /data/debug.txt
set -ex
env >> /data/debug.txt
ls -l /dev >> /data/debug.txt

# Optionen aus /data/options.json lesen
REMOTE_HOST=$(jq -r '.remote_host // "192.168.20.20"' /data/options.json)
REMOTE_PORT=$(jq -r '.remote_port // 2004' /data/options.json)
DEVICE_LINK=$(jq -r '.device_link // "/dev/ttyWMA0"' /data/options.json)

echo "Starte socat: $REMOTE_HOST:$REMOTE_PORT <-> $DEVICE_LINK"
socat PTY,link=$DEVICE_LINK,raw TCP:$REMOTE_HOST:$REMOTE_PORT
